# Generated by Django 4.1 on 2022-08-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buynow',
        ),
    ]
