# Generated by Django 4.1 on 2022-08-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentprice',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
